import glob
import re
import time

import pandas as pd
from playwright.sync_api import Playwright, sync_playwright, expect
from bs4 import BeautifulSoup


company = "Aditya Birla Capital"

def function(page, data):
    fund_selector = "#__next > div.marquee-content > div.know-our-funds > div.fundContainer > div.fundDetailsSection > div:nth-child(1) > p.detailsValue"
    nav_selector = "#__next > div.marquee-content > div.know-our-funds > div.fundContainer > div.fundDetailsSection > div:nth-child(3) > p.detailsValue"
    fund = BeautifulSoup(page.inner_html(fund_selector), 'html.parser').get_text()
    nav = BeautifulSoup(page.inner_html(nav_selector), 'html.parser').get_text()
    # data.append([company, fund, nav])
    data.append([nav])
    return data


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://lifeinsurance.adityabirlacapital.com/about-us/know-our-funds/")
    time.sleep(2)
    date_selector = "#__next > div.marquee-content > div.know-our-funds > div.fundContainer > div.fundDetailsSection > div:nth-child(4) > p.detailsValue"
    date = BeautifulSoup(page.inner_html(date_selector), 'html.parser').get_text()
    print(date)

    # data = [[company, " "],["Fund", date]]
    data = [[date]]

    page.get_by_role("button", name="Balancer Fund ").first.click()
    page.locator("li").filter(has_text="Asset Allocation Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameAsset Allocation FundSegregated Fund Identification No.ULIF03430/10/").click()
    page.get_by_role("button", name="Asset Allocation Fund ").click()
    page.get_by_text("Assure Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameAssure FundSegregated Fund Identification No.ULIF01008/07/").click()
    page.get_by_role("button", name="Assure Fund ").click()
    page.locator("li").filter(has_text="Balancer Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameBalancer FundSegregated Fund Identification No.ULIF00931/05/").click()
    page.get_by_role("button", name="Balancer Fund ").first.click()
    page.get_by_text("Builder Fund").click()
    data = function(page, data)
    #page.get_by_text("Fund NameBuilder FundSegregated Fund Identification No.ULIF00113/03/").click()
    page.get_by_role("button", name="Builder Fund ").click()
    page.get_by_text("Capped Nifty Index Fund").click()
    data = function(page, data)
    #page.get_by_text("Fund NameCapped Nifty Index FundSegregated Fund Identification No.ULIF03530/10/").click()
    page.get_by_role("button", name="Capped Nifty Index Fund ").click()
    page.get_by_text("Creator Fund").click()
    data = function(page, data)
    #page.get_by_text("Fund NameCreator FundSegregated Fund Identification No.ULIF00704/02/").click()
    page.get_by_role("button", name="Creator Fund ").click()
    page.get_by_text("Discontinued Policy Fund", exact=True).click()
    data = function(page, data)
    #page.get_by_text("Fund NameDiscontinued Policy FundSegregated Fund Identification No.ULIF02301/07").click()
    page.get_by_role("button", name="Discontinued Policy Fund ").click()
    page.get_by_text("Enhancer Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameEnhancer FundSegregated Fund Identification No.ULIF00213/03/").click()
    page.get_by_role("button", name="Enhancer Fund ").click()
    page.get_by_text("ESG").click()
    data = function(page, data)
    # page.get_by_text("Fund NameESGSegregated Fund").click()
    page.get_by_role("button", name="ESG ").click()
    page.get_by_text("FORESIGHT - 5 PAY").click()
    data = function(page, data)
    # page.get_by_text("Fund NameFORESIGHT - 5 PAYSegregated Fund Identification No.ULIF02510/02/").click()
    page.get_by_role("button", name="FORESIGHT - 5 PAY ").click()
    page.get_by_text("FORESIGHT - SINGLE PAY").click()
    data = function(page, data)
    # page.get_by_text("Fund NameFORESIGHT - SINGLE PAYSegregated Fund Identification No.ULIF02610/02/").click()
    page.get_by_role("button", name="FORESIGHT - SINGLE PAY ").click()
    page.get_by_text("Income Advantage Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameIncome Advantage FundSegregated Fund Identification No.ULIF01507/08/").click()
    page.get_by_role("button", name="Income Advantage Fund ").click()
    page.get_by_text("Income Advantage Guaranteed").click()
    data = function(page, data)
    # page.get_by_text("Fund NameIncome Advantage Guaranteed FundSegregated Fund Identification No.").click()
    page.get_by_role("button", name="Income Advantage Guaranteed").click()
    page.get_by_text("Linked Discontinued Policy").click()
    data = function(page, data)
    # page.get_by_text("Fund NameLinked Discontinued Policy FundSegregated Fund Identification No.").click()
    page.get_by_role("button", name="Linked Discontinued Policy").click()
    page.get_by_text("Liquid Plus Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameLiquid Plus FundSegregated Fund Identification No.ULIF02807/10/").click()
    page.get_by_role("button", name="Liquid Plus Fund ").click()
    page.get_by_text("Magnifier Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameMagnifier FundSegregated Fund Identification No.ULIF00826/06/").click()
    page.get_by_role("button", name="Magnifier Fund ").click()
    page.get_by_text("Maximiser Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameMaximiser FundSegregated Fund Identification No.ULIF01101/06/").click()
    page.get_by_role("button", name="Maximiser Fund ").click()
    page.get_by_text("Maximiser Guaranteed Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameMaximiser Guaranteed FundSegregated Fund Identification No.ULIF03027/").click()
    page.get_by_role("button", name="Maximiser Guaranteed Fund ").click()
    page.get_by_text("MNC fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameMNC fundSegregated").click()
    page.get_by_role("button", name="MNC fund ").click()
    page.get_by_text("Multiplier Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameMultiplier FundSegregated Fund Identification No.ULIF01217/10/").click()
    page.get_by_role("button", name="Multiplier Fund ").click()
    page.get_by_text("Nifty Alpha 50 Index Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameNifty Alpha 50 Index FundSegregated Fund Identification No.ULIF04015/").click()
    page.get_by_role("button", name="Nifty Alpha 50 Index Fund ").click()
    page.get_by_text("Nifty Midcap150 Momentum 50").click()
    data = function(page, data)
    # page.get_by_text("Fund NameNifty Midcap150 Momentum 50 IndexSegregated Fund Identification No.").click()
    page.get_by_role("button", name="Nifty Midcap150 Momentum 50").click()
    page.get_by_text("Pension Discontinued Policy").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePension Discontinued Policy FundSegregated Fund Identification No.").click()
    page.get_by_role("button", name="Pension Discontinued Policy").click()
    page.get_by_text("Pension Enrich Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePension Enrich FundSegregated Fund Identification No.ULIF00404/03/").click()
    page.get_by_role("button", name="Pension Enrich Fund ").click()
    page.get_by_text("Pension Growth Fund").click()
    data = function(page, data)
    page.get_by_role("button", name="Pension Growth Fund ").click()
    page.get_by_text("Pension Nourish Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePension Nourish FundSegregated Fund Identification No.ULIF00604/03/").click()
    page.get_by_role("button", name="Pension Nourish Fund ").click()
    page.get_by_text("Platinum Advantage Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePlatinum Advantage FundSegregated Fund Identification No.ULIF02408/09/").click()
    page.get_by_role("button", name="Platinum Advantage Fund ").click()
    page.get_by_text("Platinum Premier Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePlatinum Premier FundSegregated Fund Identification No.ULIF02203/02/").click()
    page.get_by_role("button", name="Platinum Premier Fund ").click()
    page.get_by_text("Protector Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameProtector FundSegregated Fund Identification No.ULIF00313/03/").click()
    page.get_by_role("button", name="Protector Fund ").click()
    page.get_by_text("Pure Equity Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NamePure Equity FundSegregated Fund Identification No.ULIF02707/10/").click()
    page.get_by_role("button", name="Pure Equity Fund ").click()
    page.get_by_text("Small Cap").click()
    data = function(page, data)
    # page.get_by_text("Fund NameSmall CapSegregated").click()
    page.get_by_role("button", name="Small Cap ").click()
    page.get_by_text("Super 20 Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameSuper 20 FundSegregated Fund Identification No.ULIF01723/06/").click()
    page.get_by_role("button", name="Super 20 Fund ").click()
    page.get_by_text("Titanium Fund -").click()
    data = function(page, data)
    # page.get_by_text("Fund NameTitanium Fund - 1Segregated Fund Identification No.ULIF01911/12/").click()
    page.get_by_role("button", name="Titanium Fund - 1 ").click()
    page.get_by_text("Unclaimed Maturity Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameUnclaimed Maturity FundSegregated Fund Identification No.ULIF03618/02/").click()
    page.get_by_role("button", name="Unclaimed Maturity Fund ").click()
    page.get_by_text("Value Momentum Fund").click()
    data = function(page, data)
    # page.get_by_text("Fund NameValue Momentum FundSegregated Fund Identification No.ULIF02907/10/").click()


    df = pd.DataFrame(data)
    df.to_csv(f"D:/Innover/Daily nav/Birla.csv", mode='w', header=False, index=False)

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
